# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
loader_version=0.19.3
kotlin_loader_version=1.13.13+kotlin.2.4.10
# Mod Properties
general_version=0.1
maven_group=com.bleudev
archives_base_name=ModSync
